//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IVendingMachine 
{
	IDictionary<int, IShowcaseItem> Showcase { get;set; }

	Money Balance {get;}

	void Insert(Coin coin);

	Coin[] GetChange();

	IProduct Buy(int number);
}

