//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using System.Text;

public class ProductBusket : IShowcaseItem
{

    private Stack<IProduct> _product = new Stack<IProduct>(); 
    public void Add(IProduct product)
    {
        _product.Push(product);
    }

	public IProduct Dispence()
	{
	        return _product.Pop();
	}

    public int Amount { get
    {
        return _product.Count;
    } }

    public ProductBusket(int number, Money cost)
    {
        Number = number;
        Cost = cost;
    }

    public int Number { get; private set; }

    public IProduct Product { get
    {
        return _product.Peek();
    } }

    public Money Cost { get; private set; }
}

public class BusketIsEmptyException : Exception
{
    public BusketIsEmptyException():base("Диспенсер товаров пуст")
    {
        
    }
}