//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using System.Text;

public class ProductBusket : IShowcaseItem
{

    private Stack<IProduct> _product = new Stack<IProduct>(); 
    public void Add(IProduct product)
    {
        _product.Push(product);
    }

	public IProduct Dispence()
	{
	    try
	    {

	        return _product.Pop();
	    }
	    catch (InvalidOperationException)
	    {
	        throw new BusketIsEmptyException();
	    }
	}

    public int Amount { get
    {
        return _product.Count;
    } }

    public ProductBusket(int number, Money cost)
    {
        Number = number;
        Cost = cost;
    }

    public int Number { get; private set; }

    public IProduct Product
    {
        get
        {
            return _product.Count > 0 ? _product.Peek() : null;
        }
    }

    public Money Cost { get; private set; }
}