//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachine.Domain
{
    using System.Collections.Generic;

    public interface IVendingMachine 
    {
        IDictionary<int, IShowcaseItem> Showcase { get;set; }

        Money Balance {get;}

        void Insert(Coin coin);

        Coin[] GetChange();

        IProduct Buy(int number);
    }

    public class VendingMachine : IVendingMachine
    {
        public IDictionary<int, IShowcaseItem> Showcase { get; set; }

        public Money Balance { get; private set; }

        public void Insert(Coin coin)
        {
            throw new System.NotImplementedException();
        }

        public Coin[] GetChange()
        {
            throw new System.NotImplementedException();
        }

        public IProduct Buy(int number)
        {
            throw new System.NotImplementedException();
        }
    }
}

